[package]
name = "twitter"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.4", features = ["json"] }
url = "2.1.1"
tokio = { version = "1.11.0", features = ["full"] }
serde = { version = "^1.0.130", features = ["derive"] }
serde_json = "^1.0.67"
anyhow = "1.0.32"